/* Auto-generated by format.js - Do not edit manually */

import { fileURLToPath } from 'node:url'

const DEFAULT_CONFIG = {
  printWidth: 80,
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'none',
  useTabs: false
}

const IGNORE_FILES = [
  '**/node_modules/**',
  '**/dist/**',
  '**/coverage/**',
  '**/temp/**',
  '**/.vitepress/cache/**',
  '**/.nuxt/**',
  '**/.vercel/**',
  '**/.changeset/**',
  '**/.idea/**',
  '**/.output/**',
  '**/.vite-inspect/**',
  'output/**',
  '**/CHANGELOG*.md',
  '**/*.min.*',
  '**/LICENSE*',
  '**/__snapshots__',
  '**/auto-import?(s).d.ts',
  '**/components.d.ts',
  '**/typed-router.d.ts',
  '**/pnpm-lock.yaml'
]

const king3 = (userConfig = {}) => {
  return {
    ...DEFAULT_CONFIG,
    ...userConfig,
    overrides: [
      {
        files: [...IGNORE_FILES],
        options: { requirePragma: true }
      },
      {
        files: ['**/jsr.json'],
        options: { parser: 'json-stringify' }
      }
    ],
    plugins: [fileURLToPath(import.meta.resolve('@prettier/plugin-oxc'))]
  }
}

export default king3()
