/* Auto-generated by format.js - Do not edit manually */

const king3 = (config = {}) => {
  const { printWidth = 80, ...otherConfig } = config
  return {
    printWidth,
    semi: false,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: 'none',
    useTabs: false,
    ...otherConfig,
    overrides: [
      {
        files: [
          '**/node_modules/**',
          '**/dist/**',
          '**/coverage/**',
          '**/temp/**',
          '**/.vitepress/cache/**',
          '**/.nuxt/**',
          '**/.vercel/**',
          '**/.changeset/**',
          '**/.idea/**',
          '**/.output/**',
          '**/.vite-inspect/**',
          'output/**',
          '**/CHANGELOG*.md',
          '**/*.min.*',
          '**/LICENSE*',
          '**/__snapshots__',
          '**/auto-import?(s).d.ts',
          '**/components.d.ts',
          '**/typed-router.d.ts',
          '**/pnpm-lock.yaml'
        ],
        options: { requirePragma: true }
      },
      {
        files: ['**/jsr.json'],
        options: { parser: 'json-stringify' }
      }
    ]
  }
}

export default king3()
