/* eslint-disable no-console */

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { blue, bold, cyan, gray, green, red, yellow } from 'ansis'

/**
 * Configuration paths
 */
const DIST_INDEX_PATH = join(process.cwd(), 'dist', 'index.mjs')
const PRETTIER_CONFIG_PATH = join(process.cwd(), 'prettier.config.js')

/**
 * Execute a shell command with error handling
 */
function executeCommand(command, errorMessage) {
  try {
    execSync(command, { stdio: 'inherit' })
  } catch {
    console.error(bold(red(`❌ ${errorMessage}`)))
    process.exit(1)
  }
}

/**
 * Check if dist/index.mjs exists, build if not
 */
function ensureDistIndexExists() {
  if (existsSync(DIST_INDEX_PATH)) {
    console.log(
      bold(green('✔  dist/index.mjs exists')) + gray(' → skip build\n')
    )
    return
  }

  console.log(
    yellow('📦 dist/index.mjs not found') + gray(' → running `pnpm build`...\n')
  )
  executeCommand('pnpm build', 'Build failed')

  if (!existsSync(DIST_INDEX_PATH)) {
    console.error(bold(red('❌ Build failed: dist/index.mjs still missing')))
    process.exit(1)
  }
}

/**
 * Extract king3 function source code
 */
function extractKing3Function() {
  const content = readFileSync(DIST_INDEX_PATH, 'utf8')
  const startKeyword = 'const king3'
  const startIndex = content.indexOf(startKeyword)

  if (startIndex === -1) {
    throw new Error('The king3 function was not found')
  }

  const arrowIndex = content.indexOf('=>', startIndex)
  const firstBrace = content.indexOf('{', arrowIndex)

  if (arrowIndex === -1 || firstBrace === -1) {
    throw new Error('king3 function structure is incomplete')
  }

  let braceCount = 0
  let endIndex = -1

  for (let i = firstBrace; i < content.length; i++) {
    if (content[i] === '{') braceCount++
    if (content[i] === '}') braceCount--
    if (braceCount === 0) {
      endIndex = i
      break
    }
  }

  if (endIndex === -1) {
    throw new Error('Failed to correctly match king3 function closing bracket')
  }

  const semicolonIndex = content.indexOf(';', endIndex)
  return content.slice(startIndex, semicolonIndex + 1)
}

/**
 * Generate prettier.config.js
 */
function generatePrettierConfig(king3Source) {
  const configContent = [
    '/* Auto-generated by format.js - Do not edit manually */',
    '',
    king3Source,
    '',
    'export default king3()',
    ''
  ].join('\n')

  writeFileSync(PRETTIER_CONFIG_PATH, configContent, 'utf8')

  console.log(bold(green('🎉 Generated prettier.config.js\n')))
}

/**
 * Main flow
 */
function main() {
  console.log(bold(cyan('🚀 Starting format script...\n')))

  try {
    console.log(blue('➡ Step 1: Ensure dist/index.mjs exists'))
    ensureDistIndexExists()

    console.log(blue('➡ Step 2: Extract king3 function'))
    const king3Source = extractKing3Function()

    console.log(blue('➡ Step 3: Generate prettier.config.js'))
    generatePrettierConfig(king3Source)

    console.log(bold(green('✔ Done!')))
  } catch (error) {
    console.error(bold(red('\n❌ Unexpected error occurred:')))
    console.error(red(error.message))
    process.exit(1)
  }
}

main()
