/* eslint-disable no-console */

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { blue, bold, cyan, gray, green, red, yellow } from 'ansis'

/**
 * Configuration paths
 */
const DIST_INDEX_FILE = 'index.js'
const DIST_INDEX_PATH = join(process.cwd(), 'dist', DIST_INDEX_FILE)
const PRETTIER_CONFIG_PATH = join(process.cwd(), 'prettier.config.js')

/**
 * Execute a shell command with error handling
 */
function executeCommand(command: string, errorMessage: string) {
  try {
    execSync(command, { stdio: 'inherit' })
  } catch {
    console.error(bold(red(`❌ ${errorMessage}`)))
    process.exit(1)
  }
}

/**
 * Check if dist/index.js exists, build if not
 */
function ensureDistIndexExists() {
  if (existsSync(DIST_INDEX_PATH)) {
    console.log(
      bold(green(`✔  dist/${DIST_INDEX_FILE} exists`)) +
        gray(' → skip build\n')
    )
    return
  }

  console.log(
    yellow(`📦 dist/${DIST_INDEX_FILE} not found`) +
      gray(' → running `pnpm build`...\n')
  )
  executeCommand('pnpm build', 'Build failed')

  if (!existsSync(DIST_INDEX_PATH)) {
    console.error(
      bold(red(`❌ Build failed: dist/${DIST_INDEX_FILE} still missing`))
    )
    process.exit(1)
  }
}

/**
 * Extract a constant or function from source code
 */
function extractCodeBlock(
  content: string,
  keyword: string,
  type: 'object' | 'function' = 'object'
): string {
  const startIndex = content.indexOf(keyword)

  if (startIndex === -1) {
    throw new Error(`${keyword} was not found`)
  }

  const equalsIndex = content.indexOf('=', startIndex)
  if (equalsIndex === -1) {
    throw new Error(`No equals sign found for ${keyword}`)
  }

  let searchFrom = equalsIndex

  // For arrow functions, skip to after '=>'
  if (type === 'function') {
    const arrowIndex = content.indexOf('=>', equalsIndex)
    if (arrowIndex !== -1) {
      const nextStatement = content.indexOf('const ', equalsIndex + 1)
      if (nextStatement === -1 || arrowIndex < nextStatement) {
        searchFrom = arrowIndex + 2
      }
    }
  }

  // Find first { or [
  let firstBraceIndex = -1
  for (let i = searchFrom; i < content.length; i++) {
    if (content[i] === '{' || content[i] === '[') {
      firstBraceIndex = i
      break
    }
  }

  if (firstBraceIndex === -1) {
    throw new Error(`No opening brace/bracket found for ${keyword}`)
  }

  // Count brackets to find matching closing bracket
  let braceCount = 0
  let endIndex = -1

  for (let i = firstBraceIndex; i < content.length; i++) {
    const char = content[i]

    if (char === '{' || char === '[') braceCount++
    if (char === '}' || char === ']') braceCount--

    if (braceCount === 0) {
      // Look for semicolon within 50 chars
      const searchLimit = Math.min(i + 50, content.length)
      for (let j = i + 1; j < searchLimit; j++) {
        if (content[j] === ';') {
          endIndex = j
          break
        }
        if (content[j] === '\n' && content[j + 1]?.match(/^[a-z]/i)) {
          break
        }
      }
      endIndex = endIndex === -1 ? i : endIndex
      break
    }
  }

  if (endIndex === -1) {
    throw new Error(`Failed to correctly extract ${keyword}`)
  }

  return content.slice(startIndex, endIndex + 1)
}

/**
 * Extract configuration constants and function
 */
function extractConfiguration() {
  const content = readFileSync(DIST_INDEX_PATH, 'utf8')

  console.log(gray('  → Extracting DEFAULT_CONFIG...'))
  const defaultConfig = extractCodeBlock(
    content,
    'const DEFAULT_CONFIG',
    'object'
  )

  console.log(gray('  → Extracting IGNORE_FILES...'))
  const ignoreFiles = extractCodeBlock(content, 'const IGNORE_FILES', 'object')

  console.log(gray('  → Extracting king3 function...\n'))
  const king3Function = extractCodeBlock(content, 'const king3', 'function')

  return {
    defaultConfig,
    ignoreFiles,
    king3Function
  }
}

/**
 * Generate prettier.config.js
 */
function generatePrettierConfig(config: {
  defaultConfig: string
  ignoreFiles: string
  king3Function: string
}) {
  const configContent = [
    '/* Auto-generated by format.js - Do not edit manually */',
    '',
    'import { fileURLToPath } from "url";',
    '',
    config.defaultConfig,
    '',
    config.ignoreFiles,
    '',
    config.king3Function,
    '',
    'export default king3();',
    ''
  ].join('\n')

  writeFileSync(PRETTIER_CONFIG_PATH, configContent, 'utf8')

  console.log(bold(green('🎉 Generated prettier.config.js\n')))
}

/**
 * Main generate process
 */
function generate() {
  console.log(bold(cyan('🚀 Starting generate script...\n')))

  try {
    console.log(blue(`➡ Step 1: Ensure dist/${DIST_INDEX_FILE} exists`))
    ensureDistIndexExists()

    console.log(blue('➡ Step 2: Extract configuration'))
    const config = extractConfiguration()

    console.log(blue('➡ Step 3: Generate prettier.config.js'))
    generatePrettierConfig(config)

    console.log(bold(green('✔ Done!')))
  } catch (error) {
    console.error(bold(red('\n❌ Unexpected error occurred:')))
    console.error(red((error as Error).message))
    process.exit(1)
  }
}

generate()
