/* eslint-disable no-console */

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'

import { bold, cyan, dim, green, red, yellow } from 'ansis'

/**
 * Configuration paths
 */
const DIST_INDEX_FILE = 'index.mjs'
const DIST_INDEX_PATH = join(process.cwd(), 'dist', DIST_INDEX_FILE)
const PRETTIER_CONFIG_PATH = join(process.cwd(), 'prettier.config.js')

/**
 * Execute a shell command with error handling
 */
function executeCommand(command: string, errorMessage: string) {
  try {
    execSync(command, { stdio: 'inherit' })
  } catch {
    console.error(bold(red(`❌ ${errorMessage}`)))
    process.exit(1)
  }
}

/**
 * Check if dist/index.js exists, build if not
 */
function ensureDistIndexExists() {
  if (existsSync(DIST_INDEX_PATH)) {
    console.log(
      dim('  ') +
        green(`✓ dist/${DIST_INDEX_FILE} exists`) +
        dim(' (skip build)')
    )
    return
  }

  console.log(
    dim('  ') +
      yellow(`⚠️  dist/${DIST_INDEX_FILE} not found, running build...`)
  )
  executeCommand('pnpm build', 'Build failed')

  if (!existsSync(DIST_INDEX_PATH)) {
    console.error(
      bold(red(`\n  ❌ Build failed: dist/${DIST_INDEX_FILE} still missing`))
    )
    process.exit(1)
  }
  console.log(dim('  ') + green(`✓ Build completed`))
}

/**
 * Extract a constant or function from source code
 */
function extractCodeBlock(
  content: string,
  keyword: string,
  type: 'object' | 'function' = 'object'
): string {
  const startIndex = content.indexOf(keyword)

  if (startIndex === -1) {
    throw new Error(`${keyword} was not found`)
  }

  const equalsIndex = content.indexOf('=', startIndex)
  if (equalsIndex === -1) {
    throw new Error(`No equals sign found for ${keyword}`)
  }

  let searchFrom = equalsIndex

  // For arrow functions, skip to after '=>'
  if (type === 'function') {
    const arrowIndex = content.indexOf('=>', equalsIndex)
    if (arrowIndex !== -1) {
      const nextStatement = content.indexOf('const ', equalsIndex + 1)
      if (nextStatement === -1 || arrowIndex < nextStatement) {
        searchFrom = arrowIndex + 2
      }
    }
  }

  // Find first { or [
  let firstBraceIndex = -1
  for (let i = searchFrom; i < content.length; i++) {
    if (content[i] === '{' || content[i] === '[') {
      firstBraceIndex = i
      break
    }
  }

  if (firstBraceIndex === -1) {
    throw new Error(`No opening brace/bracket found for ${keyword}`)
  }

  // Count brackets to find matching closing bracket
  let braceCount = 0
  let endIndex = -1

  for (let i = firstBraceIndex; i < content.length; i++) {
    const char = content[i]

    if (char === '{' || char === '[') braceCount++
    if (char === '}' || char === ']') braceCount--

    if (braceCount === 0) {
      // Look for semicolon within 50 chars
      const searchLimit = Math.min(i + 50, content.length)
      for (let j = i + 1; j < searchLimit; j++) {
        if (content[j] === ';') {
          endIndex = j
          break
        }
        if (content[j] === '\n' && content[j + 1]?.match(/^[a-z]/i)) {
          break
        }
      }
      endIndex = endIndex === -1 ? i : endIndex
      break
    }
  }

  if (endIndex === -1) {
    throw new Error(`Failed to correctly extract ${keyword}`)
  }

  return content.slice(startIndex, endIndex + 1)
}

/**
 * Extract configuration constants and function
 */
function extractConfiguration() {
  const content = readFileSync(DIST_INDEX_PATH, 'utf8')

  console.log(`${dim('  → ')}Extracting DEFAULT_CONFIG...`)
  const defaultConfig = extractCodeBlock(
    content,
    'const DEFAULT_CONFIG',
    'object'
  )

  console.log(`${dim('  → ')}Extracting IGNORE_FILES...`)
  const ignoreFiles = extractCodeBlock(content, 'const IGNORE_FILES', 'object')

  console.log(`${dim('  → ')}Extracting king3 function...`)
  const king3Function = extractCodeBlock(content, 'const king3', 'function')

  console.log(dim('  ') + green('✓ All configurations extracted'))

  return {
    defaultConfig,
    ignoreFiles,
    king3Function
  }
}

/**
 * Generate prettier.config.js
 */
function generatePrettierConfig(config: {
  defaultConfig: string
  ignoreFiles: string
  king3Function: string
}) {
  const configContent = [
    '/* Auto-generated by prettiergen - Do not edit manually */',
    '',
    config.defaultConfig,
    '',
    config.ignoreFiles,
    '',
    config.king3Function,
    '',
    'export default king3();',
    ''
  ].join('\n')

  writeFileSync(PRETTIER_CONFIG_PATH, configContent, 'utf8')

  console.log(dim('  ') + green('✓ Written to ') + cyan('prettier.config.js'))
}

/**
 * Main prettiergen process
 */
function prettiergen() {
  try {
    console.log(bold(cyan('🚀 Starting prettier config generation...\n')))

    console.log(`${bold('Step 1: ')}Ensure build artifacts exist`)
    ensureDistIndexExists()

    console.log(`${bold('\nStep 2: ')}Extract configurations`)
    const config = extractConfiguration()

    console.log(`${bold('\nStep 3: ')}Generate prettier.config.js`)
    generatePrettierConfig(config)

    console.log(bold(green('\n🎉 Prettier config generated successfully!\n')))
  } catch (error) {
    console.error(
      `${
        bold(red('\n❌ Generation failed: ')) + red((error as Error).message)
      }\n`
    )
    process.exit(1)
  }
}

prettiergen()
